Fixes newline between close brace and endif bug
Unity-Technologies/uncrustify pull request #22
Opened 2017-10-09 10:37 UTC by KalyanaChakravarthi

The changes done to fix the bug 
# 1292: Investigate extra newline added between } and #endif in C#

2017-10-09 12:27 UTC, mihaipopescu requested changes
I have noticed that there were some other changes in existing test output files. Every change on them is usually frowned upon but they can be accepted if you can make a good case out of it.

In this particular case, apparently the bugfix shouldn't have influenced those tests at all because you have essentially added an exception to the `nl_after_func_body_class` option which should be applied, as described in the description, on _the number of newlines after '}' of a multi-line function body in a class declaration_ and not on after regular function bodies. That's the `nl_after_func_body` and probably somehow they influence each other or something else happens.

Anyway, it seems you have uncovered another malfunction which must be fixed first before making this change but definitely this change should not influence those other tests.

2017-10-09 12:27 UTC, mihaipopescu commented on src/newlines.cpp
> +            bool flag = !(next != nullptr && (next->parent_type == CT_PP_ELSE || next->parent_type == CT_PP_ENDIF));
`flag` is a very vague variable name. A better name would be `is_closing_preproc_block`. This will force you not to use a negated value which can create confusions.

2017-10-09 12:27 UTC, mihaipopescu commented on src/newlines.cpp
> +                  if (cpd.settings[UO_nl_after_func_body_class].u != pc->nl_count)
I don't really see the point of nesting the `if`s here.

2017-10-10 03:56 UTC, KalyanaChakravarthi commented on src/newlines.cpp
> +            bool flag = !(next != nullptr && (next->parent_type == CT_PP_ELSE || next->parent_type == CT_PP_ENDIF));
Hi Mihai,
Thanks for the review we will update the code as suggested by you.

2017-10-11 21:27 UTC, hschlichter requested changes
I don't think it should remove newlines. That fact the tests have been modified is a little worrying to me.

It should preserve whatever newlines exist before the #endif, but not create a new one.

I think that if we don't want to have the any newlines before #endif, it should be a new separate configuration option that can be enabled/disabled isolated from this.

2017-10-13 05:30 UTC, KalyanaChakravarthi commented
As this is a configuration change related issue, closing the pull request.

2017-10-13 05:30 UTC, closed without merging