Fixed issue #1289
Unity-Technologies/uncrustify pull request #41
Opened 2017-11-03 07:20 UTC by KalyanaChakravarthi

Fixed issue of bad tokenization of double pointers

2017-11-07 12:04 UTC, hschlichter requested changes
This doesn't at all solve the "bad tokenization of double pointers" issue.

As far as we can see, the reason why the travis and appveyor tests are green is because it ignores the function prototypes that have the __declspec. Which is super specific and wrong.

Furthermore, this causes major regressions in our code base, because the default behavior is changing in a dramatic way.

In a meeting some weeks ago, we talked about how to solve this. Currently uncrustify doesn't know enough about the type information when parsing function prototypes. This could be solved by running through the parsing a second time. We take this approach in several places. If you have any doubts about to actually fix this issue, reach out to us on #devs-uncrustify so we can talk about the solution.

2017-11-07 12:04 UTC, hschlichter commented on src/keywords.cpp
> +   { "__declspec",         CT_DECLSPEC,      LANG_C | LANG_CPP | LANG_CS                                                 },
__declspec is a C/C++ specific modifier. Why is C# added as a language?

2017-11-07 12:04 UTC, hschlichter commented on src/token_enum.h
> +   CT_DECLSPEC,         // __declspec
It's way too specific to add as a token. If anything, it should be something about the storage class.

2017-11-07 12:04 UTC, hschlichter commented on src/space.cpp
> +      return(AV_IGNORE);
Why are you ignoring here? Doesn't make much sense.

2017-11-09 10:08 UTC, KalyanaChakravarthi commented
test this please

2017-11-14 08:26 UTC, hschlichter commented
There is still a diff on the unity-diff-checker. It removes a single line break. Which on the surface wouldn't seem like a big deal(and you can definitely argue that the line break should be removed). But the question is why does it do that?

2017-11-14 08:52 UTC, KalyanaChakravarthi commented
Hi Henrik,
Can you please forward the test case for the above scenario?

2017-11-14 09:18 UTC, aneesh1127 commented
@unitydevtools test

2017-12-04 12:16 UTC, merged