FIXES 10043 STAGING Scenario
Unity-Technologies/uncrustify pull request #84
Opened 2018-01-12 07:50 UTC by satishp87

by enabling the option converts templates to multiliner

2018-01-13 21:12 UTC, mihaipopescu requested changes
Looks good. Small changes.

2018-01-13 21:12 UTC, mihaipopescu commented on src/newlines.cpp
> +               if (chunk_is_opening_brace(chunk_get_next_ncnl(pc)) || chunk_is_paren_open(chunk_get_next_ncnl(pc)))
You can cache the token

2018-01-13 21:12 UTC, mihaipopescu commented on src/options.cpp
> +                  "Add  newline between '>()' or '>' and '{' .");
Remove one space after add

2018-01-13 21:12 UTC, mihaipopescu commented on src/options.h
> +   UO_nl_template,                    //Add  newline between '>()' or '>' and '{' .
Add space before add. Strange that uncrustify doesn't enforce that.

2018-01-13 21:12 UTC, mihaipopescu commented on src/options.cpp
> +                  "Add  newline between '>()' or '>' and '{' .");
I'd also make the name a bit less generic.

2018-02-12 08:29 UTC, hschlichter approved these changes
Looks good

2018-02-12 08:29 UTC, hschlichter commented
@mihaipopescu does fixes you asked for look good?

2018-02-12 10:51 UTC, satishp87 commented
@hschlichter 
All changes requested by @mihaipopescu are addressed.

2018-03-08 12:53 UTC, mihaipopescu approved these changes

2018-03-15 07:22 UTC, merged